# LLM增强的PPT审查配置

# 基础格式设置
jp_font_name: "Meiyou UI"
min_font_size_pt: 12

# 缩略语设置
acronym_min_len: 2
acronym_max_len: 8

# 颜色设置
color_count_threshold: 5

# 输出格式
output_format: "md"

# 自动修复开关
autofix_font: false
autofix_size: false
autofix_color: false

# LLM配置（默认启用）
llm_enabled: true
llm_model: "deepseek-chat"  # 默认使用 DeepSeek 模型
llm_temperature: 0.2
llm_max_tokens: 1024

# 审查维度开关
review_format: true      # 格式规范审查
review_logic: true       # 内容逻辑审查
review_acronyms: true    # 缩略语审查
review_fluency: true     # 表达流畅性审查

# 词库路径（可选）
jp_terms_path: "dicts/jp_it_terms.txt"
term_mapping_path: "dicts/term_mapping.csv"
