# PPT审查工具配置文件

# 字体配置
jp_font_name: "Meiryo UI"  # 日文字体统一
min_font_size_pt: 12        # 最小字号（磅）

# 颜色配置
color_count_threshold: 5    # 颜色数量阈值

# 输出格式
output_format: "md"         # 报告格式：md | html

# 自动修复开关
autofix_font: false         # 是否自动修复字体
autofix_size: false         # 是否自动修复字号
autofix_color: false        # 是否自动修复颜色

# 词库路径（可选）
jp_terms_path: "dicts/jp_it_terms.txt"      # 日语IT术语词典
term_mapping_path: "dicts/term_mapping.csv"  # 术语映射表

# LLM配置
llm_enabled: true             # 是否启用LLM审查
llm_provider: "deepseek"      # LLM提供商：deepseek, openai, anthropic, local, kimi, bailian
llm_model: "deepseek-chat"    # 模型名称
llm_api_key: "sk-0b582422a77448fbaacc018d714af908"  # API密钥（请替换为您的实际密钥）
llm_base_url: ""             # 基础URL（留空则按provider自动推断）
llm_endpoint: ""              # 自定义端点（可留空，根据 base_url 自动拼接）
llm_temperature: 0.2          # 温度参数（越低越确定）
llm_max_tokens: 4000         # 最大token数
llm_use_proxy: false          # 是否使用代理（默认关闭）
llm_proxy_url: ""             # 代理URL（如：http://proxy.company.com:8080）

# 支持的模型列表
llm_models:
  deepseek:
    - "deepseek-chat"
    - "deepseek-coder"
  openai:
    - "gpt-4"
    - "gpt-3.5-turbo"
    - "gpt-4-turbo"
  anthropic:
    - "claude-3-opus"
    - "claude-3-sonnet"
    - "claude-3-haiku"
  kimi:
    - "moonshot-v1-8k"
    - "moonshot-v1-32k"
    - "moonshot-v1-128k"
  bailian:
    - "qwen2.5-7b"
    - "qwen2.5-14b"
  local:
    - "qwen2.5-7b"
    - "llama3.1-8b"

# 审查维度开关
llm_review:
  review_format: true           # 格式规范审查
  review_logic: true            # 内容逻辑审查
  review_acronyms: true          # 缩略语审查
  review_fluency: true           # 表达流畅性审查

# 审查规则配置
rules_review:
  font_family: true           # 启用字体族检查
  font_size: true             # 启用字号检查
  color_count: true           # 启用颜色数量检查
  theme_harmony: true         # 启用主题一致性检查
  acronym_explanation: true   # 启用缩略语解释检查

# 报告配置
report:
  include_summary: true       # 包含问题汇总
  include_details: true       # 包含详细问题
  include_suggestions: true   # 包含改进建议
  include_statistics: true    # 包含统计信息

